platform :ios, '8.0'
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

target 'SVDouYinOC' do

  pod 'AFNetworking'
  pod 'FMDB'
  pod 'TYPagerController'
  pod 'Masonry'
  pod 'YYModel'
  pod 'YYImage'
  pod 'KVOController', '~> 1.2.0'
  pod 'LBXScan/LBXNative'
  pod 'LBXScan/UI','~> 2.3'
  pod 'SDWebImage'
  pod 'SDWebImage/WebP'
  pod 'Bugly', '~> 2.5.0'
  pod 'WSLWaterFlowLayout', '~> 1.0.1'
  pod 'SocketRocket'


  target 'SVDouYinOCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SVDouYinOCUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

# 第三方框架 deployment target  警告的问题
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f <= 8.0
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '8.0'
      end
    end
  end
end
